spring:
  datasource:
    generate-unique-name: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 2MB
---
spring:
  config:
    activate:
      on-profile: dev
socio:
  upload-path: storage-dev
---
spring:
  config:
    activate:
      on-profile: production
socio:
  upload-path: storage-production
